### ISSUE TITLE
release latest version

### ISSUE THREAD

**Issue by aggarwalankush** [ionic-team/ionic-storage#108]
I'm using `storage.clear()` method but typescript throws error as it returns `Promise<null>`. It's fixed in this commit https://github.com/driftyco/ionic-storage/commit/2c7748f02e607ef8e96776b778832a437ce6caa5#diff-89e9fd90feb499cac1623bd562b7c8e3L194

Can you release v2.0.2?

**Comment by plrthink** [comment]
Also I can check that the `OpaqueToken` has been removed to support Angular 5 but not released yet. 

need a new release otherwise, it can't compile with Angular 5.

**Comment by mhartington** [comment]
Closing as this is most likely not relevant any more. Please open a new issue if this is still a problem. Thanks!
