### ISSUE TITLE
storage.get behavior when getting already removed data 

### ISSUE THREAD

**Issue by karimabdelhakim** [ionic-team/ionic-storage#117]
when i try do something like this 
` this.storage.get('user').then((user) => {
console.log(user);
})
`
when user doesn't exist , _then_ enters and user is null , is that normal behavior 
or it should fire catch which didn't actually fire?

**Comment by NoNameProvided** [comment]
It's the expected behaviour.

**Comment by karimabdelhakim** [comment]
in other part in my app same code with _.catch_ and it actually fired , any idea why this might happen,
like a scenario where this would happen ?

**Comment by NoNameProvided** [comment]
Trying to read a non-existing value is not considered an error. 

This was a decision which was made while writing the lib, I don't see any particular reason for it, they just decided to do it this way. If you really interested in the reasons, some of the ionic core members will be able to tell you.

**Comment by karimabdelhakim** [comment]
your answer was enough, thanks
