### ISSUE TITLE
Android: data persists even after uninstall. Why?

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic-storage#118]
Using Ionic Storage with default configuration as documented:

```
import { IonicStorageModule } from '@ionic/storage';

@NgModule({
  declarations: [
    // ...
  ],
  imports: [      
    BrowserModule,
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot()
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    // ...
  ],
  providers: [
    // ...
  ]
})
export class AppModule {}
```

On Android, the data persists even after uninstalling and reinstalling the app. Why?

**Comment by janpio** [comment]
Because local storage is probably synched to the cloud and redownloaded after reinstalling your app. There are Cordova settings to disable this, some googling should help you find them (I don't have them handy right now). Please let us know if you find them.

**Comment by shawnlan** [comment]
You are right. However, I only found the configuration for iOS: Use the location or iosDatabaseLocation option in sqlitePlugin.openDatabase() to store the database in a subdirectory that is NOT backed up to iCloud, as described in the section below.

> Use the location or iosDatabaseLocation option in sqlitePlugin.openDatabase() to store the database in a subdirectory that is NOT backed up to iCloud, as described in the section below.

For Android, is this behavior completely under users' control?

**Comment by janpio** [comment]
That is the configuration for SQLite. 

I found an older forum post that I did on this: https://forum.ionicframework.com/t/data-does-not-cleared-in-ionic-storage/88538/4?u=sujan12

**Comment by shawnlan** [comment]
For Android, that's all I need. Thanks!

For iOS, since Ionic Storage uses this plugin (https://github.com/litehelpers/Cordova-sqlite-storage) on mobile devices, I don't think `BackupWebStorage` has any effect, as stated in the plugin readme.

**Comment by kotrakrishna** [comment]
For android 
[do config.xml changes](https://stackoverflow.com/a/55174277/1504589)
