### ISSUE TITLE
Ionic Storage is lying about result for driver webSQLStorage

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-storage#119]
Javascript "allows" properties on arrays, because everything is an array in Javascript. Of course this only seems to work in some browsers: Chrome allows this, Firefox doesn't.

When you try to `storage.set` such an array on iOS with driver `webSQLStorage` (default for simulated iOS in Chrome browser), it will tell you that it saved the array as you gave it to the function. But if you later storage.get the key you used, you will receive and empty array `[]` back. This is confusing and a source for bugs.

On Android (device or emulated in Chrome via `ionic serve`) everything works as expected.
On iOS (emulated in Chrome via `ionic serve`) an empty array is returned from storage. 
On iOS the default driver is asyncStorage on real devices.
(Testing in Firefox  via `ionic serve` swallows the porperty from the beginning.)

I created a repo to try this at https://github.com/janpio/ionic-storage-brokenarray

Is this a problem of Ionic Storage, localForage or just a Javascript mess?

**Comment by jesusbotella** [comment]
It may be something related to localForage/webSQLStorage, but not related to ionic storage as it is only a wrapper for localForage ;)
