### ISSUE TITLE
WebSQL db cleared on refresh

### ISSUE THREAD

**Issue by jamesdixon** [ionic-team/ionic-storage#123]
Hi, 

When testing in the browser (latest Chrome on Mac), the WebSQL db created by Storage is cleared whenever the browser refreshes. Do I need to do something special to make it persist?

Running Ionic 3.9.2 and Storage 2.0.1.

Thanks!

**Comment by andrei-myonlinepresence** [comment]
Hi James, why did you close this? I'm experiencing the same issue :/

**Comment by mtshare** [comment]
Hi, same for me. Any solutions?
