### ISSUE TITLE
DB from ionic app & background service are different

### ISSUE THREAD

**Issue by goleary** [ionic-team/ionic-storage#125]
I have an ionic app that uses ionic-storage.  I also have a native android background service that generates a separate webview to do work outside of the ionic app.  This service needs to write to the app's storage. I am using the same config (`name` & `storeName`) for both of these storage objects but they seem to be accessing completely different spaces. Has anyone else encountered a similar problem or know how I might be able to remedy this?

**Comment by mhartington** [comment]
Typically if you're using web-based storage methods (localstorage,indexedDB) you will have different storage instances for each webview. Even though the app is the same, the separate webview gets it's own storage "bucket". An option is to use the sqlite adapter which bypasses the browser storage mechanism. This "should" use the same storage instance between both webviews.

**Comment by goleary** [comment]
using:
![image](https://user-images.githubusercontent.com/16123225/45325325-76f48380-b505-11e8-919b-335da78d66cc.png)
I was able to get them to both access the same storage area.
