### ISSUE TITLE
OpaqueToken deprecated in Angular 5

### ISSUE THREAD

**Issue by GabberMan** [ionic-team/ionic-storage#126]
This module has stopped working since OpaqueToken is deprecated in the latest version of Angular.

**Comment by Kamule42** [comment]
The changelog indicates that  `InjectionToken` comes in replacement.

https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

**Comment by GabberMan** [comment]
I know, but the module does not ;)

**Comment by mtsgrd** [comment]
How come this issue was closed? This plugin currently seems incompatible with Cordova 3.9.2.
