### ISSUE TITLE
Use --prod compile error

### ISSUE THREAD

**Issue by coloz** [ionic-team/ionic-storage#129]
error info：
`[13:47:07]  ngc started ...
Error: Metadata version mismatch for module C:/Users/coloz/Desktop/iotapp/node_modules/@ionic/storage/dist/src/storage.d.ts, found version 4, expected 3`

I tried removing node_modules and restarting npm install, but that still does not work

**Comment by ramoncarreras** [comment]
Yes, I'm experiencing this same error.

Downgrade to 2.0.1 version solves the problem for me.

`npm install --save @ionic/storage@2.0.1`

Anyway, it must be fixed in future versions.

**Comment by mhartington** [comment]
Hi there! Going to close this as I cannot replicate this. If there is still a problem, please open a new issue.
