### ISSUE TITLE
"isTrusted":True Error, with unexpected EOF

### ISSUE THREAD

**Issue by tgensol** [ionic-team/ionic-storage#130]
Hi there,

I was getting an error with Sentry for weeks : 

`{"isTrusted":True}`

That was really coming from nowhere (javascript logger). Then, I finally had it explicitly on my simulator : 

`unexpected EOF`

I finally found that I saved this character with the ionic storage in a string : 
`\u2028`

When I was reading the value with storage.get, the error appeared, but was not firing from the promise, and it was really hard to find. The only solution I found was to remove the storage and do not store it and replace it,

Hope this helps,
Regards

**Comment by tgensol** [comment]
Finally it was this special string : U+2028

No check is done for U+2028 and U+2029 before saving it to the localStorage ?

**Comment by tgensol** [comment]
The issue is really problematic. I had to create a function to check every data before I use storage.set....

**Comment by tgensol** [comment]
You tried to save one of these characters : U+2028 and/or U+2029, which are hidden characters for us, but not for the memory. The localForage can store it, but cannot read it after that and you have the `{ "isTrusted": True }` on Sentry, and, if you have the error in  your device or simulator : `unexpected EOF`, every time you will try to load the data (and it will fail)

The only solution I found was to : find where this character is, remove the data your stored on the device and fix your data on your server.

On my side I have now a function that is looking for this character every time I am saving a string (in an array, or an object or a string) : `.replace(/\u2028/g, "").replace(/\u2029/g, "")`...

Good luck !

**Comment by mburger81** [comment]
Now I don't think I have the same problem as you, in my case the error is completely randomized. And on simulator I never got EOF error.

But honestly, that was not my question. My question was If you gently can help us on configuring sentry for ionic? 

We are not able to get it work, do you configure it like this, we found this on a [HOWTO ionic+sentry](https://gonehybrid.com/how-to-log-errors-in-your-ionic-2-app-with-sentry/)

```
Raven
    .config(
        'https://abcdef@sentry.io/123456789',
        {
            release: '0.0.15',
            dataCallback: data => {

                if (data.culprit) {
                    data.culprit = data.culprit.substring(data.culprit.lastIndexOf('/'));
                }

                var stacktrace = data.stacktrace ||
                                    data.exception &&
                                    data.exception.values[0].stacktrace;

                if (stacktrace) {
                    stacktrace.frames.forEach(function (frame) {
                        frame.filename = frame.filename.substring(frame.filename.lastIndexOf('/'));
                    });
                }
            }
        }
    )
    .install();
```

**Comment by tgensol** [comment]
Yes I did, I have the same code.

Did you change the ErrorHandler too ? especially in the AppModule.

**Comment by mburger81** [comment]
Yes, this is my Custom error handler, and as you can see, I only try to upload the error on sentry on production mode (which also is not working, it is uploading also on DEV some errors but I think this is a Raven and not my behavior)

```
import { IonicErrorHandler, ToastController } from 'ionic-angular';
import Raven from 'raven-js';

Raven
    .config(
        'https://abcdef@sentry.io/123456789',
        {
            release: '0.0.15',
            dataCallback: data => {

                if (data.culprit) {
                    data.culprit = data.culprit.substring(data.culprit.lastIndexOf('/'));
                }

                var stacktrace = data.stacktrace ||
                                    data.exception &&
                                    data.exception.values[0].stacktrace;

                if (stacktrace) {
                    stacktrace.frames.forEach(function (frame) {
                        frame.filename = frame.filename.substring(frame.filename.lastIndexOf('/'));
                    });
                }
            }
        }
    )
    .install();

export class LanthingsErrorHandler extends IonicErrorHandler {

    constructor(private toastCtrl: ToastController) {
        super();
    }

    handleError(error: any): void {
        super.handleError(error);

        // show toast message for Unexpected error only if not in dev mode
        // in dev mode ionic shows error message in IonicErrorHandler
        if(!((<any>window)['IonicDevServer'])) {
            let toast = this.toastCtrl.create({
                message: 'Unexpected error!!',
                duration: 3000,
                position: 'bottom'
            });

            toast.present();

            // log error to sentry
            try {
                Raven.captureException(error.originalError || error);
            } catch (e) {
                // do nothing
            }
        }
    }
}
```

So how do you upload the files, and which files do you upload??
We have plain .js files in /www/build and .js.map files in .sourcemaps folder.

So we are not sure, does we need both of them on sentry, and if yes how should we them upload, wy try to do it with two commands, but it does not work as expected.


```
sentry-cli releases -o blabla -p blabla files 0.0.15 upload-sourcemaps --url-prefix / .sourcemaps
sentry-cli releases -o blabla -p blabla files 0.0.15 upload-sourcemaps --url-prefix / www/build
```

**Comment by tgensol** [comment]
Please email me thibaut@appchoose.io, this has nothing to do with my issue, thanks
