### ISSUE TITLE
storage.set fails silently

### ISSUE THREAD

**Issue by ADCJustinH** [ionic-team/ionic-storage#131]
using ionic storage with default settings (thus websql default on chrome) the following is happening without throwing any errors:

 this.storage.set(this.currentAccount.id + '__' + key, val) --works
 this.storage.set(this.currentAccount.id + '_' + key, val) --fails but does not inform

1ba38859-dd16-45f7-aa2f-3ac12e47b35e_cardService.cards.localCard_14553291"   -bad key
1ba38859-dd16-45f7-aa2f-3ac12e47b35e__cardService.cards.localCard_14553291"   -good key

any ideas?

**Comment by thgreasi** [comment]
Can you share a complete key value pair sample that fails?

**Comment by ADCJustinH** [comment]
I'm afraid I can no longer replicate this after reinstalling all dependencies @latest
