### ISSUE TITLE
IndexedDB is not available on Safari 11.0.2

### ISSUE THREAD

**Issue by salbahra** [ionic-team/ionic-storage#133]
Testing `ionic-storage` on various browsers I found Safari is not correctly using IndexedDB. Looking at the method: https://github.com/localForage/localForage/blob/master/src/utils/isIndexedDBValid.js we find it's checking for `window.fetch` to detect Safari but it's polyfilled by Ionic so this check fails. Specifically, it's looking for the string `[native code]`.

This was discussed here: https://github.com/localForage/localForage/pull/733 and I was told this check didn't even exist in localForage 1.4.x. Reviewing the code indeed it shows all user agent's with  the string `Safari` will be rejected.

Can we explore updating to localForage 1.5.x (and also monkey patching it's check as shown here: https://github.com/localForage/localForage-compatibility-1-4/blob/master/dist/localforage-compatibility-1-4.js#L53-L58)? As I understand it this ability to monkey patch did not exist on 1.4.x.

Or, do we have some other solution to force the use of IndexedDB on Safari?

**Comment by salbahra** [comment]
@thgreasi has offered his expertise to help us get this resolved.

As this also affects mobile Safari I consider this a show stopping bug. So hopefully collectively we can come to a solution :)

**Comment by salbahra** [comment]
I have added a new PR which simply updates to the latest version of LocalForage. This will allow developers to patch the `_support` flag of the driver allowing us to bypass this arbitrary limitation.

**Comment by mhartington** [comment]
Thanks for the PR! This is available in 2.2.0
