### ISSUE TITLE
DevApp LiveReload issue 

### ISSUE THREAD

**Issue by phillipzada** [ionic-team/ionic-storage#144]
When using the DevApp and you make a code change intermediately you lose storage (80% of the time)  and you end up in a stuck promise.

This issue was annoying AF to find but I think i've pinpointed the culprit. Looks like it has to do with the   LocalForage.defineDriver promise not getting resolved (moving to the next then function).

I'm also getting the common errors:
```
deviceready has not fired after 5 seconds.
Channel not fired: onFileSystemPathsReady
Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an            inconsistent state. Try removing plugins from plugins/ and reinstalling them.
```
which started this journey to find out what is going on. I tried solutions such as remove/add/remove/add platforms and plugins with no luck, even tried a fresh project with no avail.

I'm not too familiar on the insides of the DevApp and hope this can help resolve this issue.

### Steps to reproduce

1. To replicate, open storage.js file in your node_modules and add console.logs in the constructor
```
function Storage(config) {
        var _this = this;
        this._driver = null;

        console.log('******STEP 0');
        this._dbPromise = new Promise(function (resolve, reject) {
            var db;
            var defaultConfig = getDefaultConfig();
            var actualConfig = Object.assign(defaultConfig, config || {});
            console.log('******STEP 0.1');
            LocalForage.defineDriver(CordovaSQLiteDriver).then(function () {
                console.log('******STEP 1');
                db = LocalForage.createInstance(actualConfig);
            })
                .then(function () {console.log('******STEP 2'); return db.setDriver(_this._getDriverOrder(actualConfig.driverOrder)); })
                .then(function () {
                    console.log('******STEP 3');
                _this._driver = db.driver();
                resolve(db);
            })
                .catch(function (reason) { return reject(reason); });
        });
    }
```
2. In you app.component.ts file create an interval to run in your constructor
```
    setInterval(() => {
      console.log(JSON.stringify(storage, null, 4));
    }, 5000);
```
3. Next start your app using `ionic serve -c `
4. Open the DevApp and select your app, Once loaded you should see your storage object every 5000 ms
```
{ "_driver": "cordovaSQLiteDriver", "_dbPromise": { "__zone_symbol__state": true,
            "__zone_symbol__value": { "INDEXEDDB": "asyncStorage", "LOCALSTORAGE": "localStorageWrapper", "WEBSQL":
            "webSQLStorage", "_defaultConfig": { "description": "", "driver": [ "asyncStorage", "webSQLStorage",
            "localStorageWrapper" ], "name": "localforage", "size": 4980736, "storeName": "keyvaluepairs", "version": 1
            }, "_config": { "description": "", "driver": "cordovaSQLiteDriver", "name": "_ionicstorage", "size":
            4980736, "storeName": "_ionickv", "version": 1, "driverOrder": [ "sqlite", "indexeddb", "websql",
            "localstorage" ] }, "_driverSet": { "__zone_symbol__state": true }, "_ready": null, "_dbInfo": null,
            "_driver": "cordovaSQLiteDriver" } } }
```

4. Make a change to your code and you save, you then see in the logs
```
{ "_driver": null, "_dbPromise": { "__zone_symbol__state": null, "__zone_symbol__value": [] } }
```
The logs also show it is stopping and the console.log 0.1 point just before LocalForage.defineDriver

The kicker is if i perform a localstorage action i.e. set/get 20/30secs after the app has loaded, it works...

### Environment
cli packages: (C:\ProgramData\nvm\v8.9.1\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.1
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Android\android-sdk

Misc:

    backend : pro

**Comment by mhartington** [comment]
Closing as devapp has been sunset.
