### ISSUE TITLE
TypeScript error with await

### ISSUE THREAD

**Issue by HZooly** [ionic-team/ionic-storage#147]
` Operand for 'await' does not have a valid callable 'then' member.`

I got this error when I try to build for Android device: `ionic cordova build android`

It happens because of this instruction: `await this.storage.clear()`

In Typescript declaration file of Storage, _clear_ method is defined as returning a promise of type **null**.

Switching this type to **any** solves the build issue.

`clear(): Promise<any>;`

Should I do a pull request, or are they side effects that could break the package?

**Edit**: Or maybe can I just wrap the storage.clear call in an await custom method?

**Comment by mhartington** [comment]
Hi there! I'm unable to replicate this error. `Promise<void>` is a valid type for a promise, so not sure whats going on there. I'm going to close this as I cannot replicate it. If the problem still appears, please open a new issue
