### ISSUE TITLE
Cannot read property 'defineDriver' of undefined

### ISSUE THREAD

**Issue by BigGillyStyle** [ionic-team/ionic-storage#148]
I am using Jest to test an Ionic/Angular application, and I get the following console error (which does *not* cause a test failure) when I run my tests:

```
    console.error node_modules/zone.js/dist/zone.js:665
      Unhandled Promise rejection: Cannot read property 'defineDriver' of undefined ; Zone: ProxyZone ; Task: null ; Value: TypeError: Cannot read property 'defineDriver' of undefined
          at /my-project/node_modules/@ionic/storage/dist/storage.js:113:25
          at new ZoneAwarePromise (/my-project/node_modules/zone.js/dist/zone.js:891:33)
...
```

Angular: 5.2.10
ionic-angular: 3.9.2
ionic/storage: 2.1.3
Node: 8.9.4
NPM: 5.8.0

In my spec setup I do have in my imports section: `IonicStorageModule.forRoot({ driverOrder: ['localstorage'] })`, and for Jest I am using 'jest-localstorage-mock'.  I have Googled and tried different remedies offered, but I continue to get this message.

The "offending" line in code seems to be this one: https://github.com/ionic-team/ionic-storage/blob/master/src/storage.ts#L120  I have verified that the localforage package is in my node_modules folder.

Let me know what other information I could provide that might be helpful.

**Comment by edupeeth** [comment]
I am facing the same issue when I try to use my code in print values in the console of admin section for below URL
https://ionic-uazaj3.stackblitz.io

**Comment by mhartington** [comment]
Please update to 2.2.0. There were some issue with how this library was packaged, which made testing difficult. This should be resolved now.
