### ISSUE TITLE
how to get storage "uset" value

### ISSUE THREAD

**Issue by bagefly** [ionic-team/ionic-storage#150]
In a typescript file, when I use following code, value returns a ts promise object,not a plain object and "uset" original value.
`let value = storage.get("uset").then(
      (data) => data
    );`
console.log(value); //the result in the following code
`t {__zone_symbol__state: null, __zone_symbol__value: Array(0)}`

**Comment by mhartington** [comment]
This is because you are logging the promise, and not the returned value. 

Do

```
let value = null;
storage.get("uset").then( (data) => value = data )
console.log(value);
```
