### ISSUE TITLE
Storage not finding files saved with keys with dots "."

### ISSUE THREAD

**Issue by sonnenhohl** [ionic-team/ionic-storage#156]
The storage.get(key) method returns null if the key name contains dots.

Example file name:

"file-DEVICE800-0.12.json"

This error occurs on Android and on IOS.

**Comment by mhartington** [comment]
So Ionic storage isn't doing anything particular to the key when passed to `get`, so I'm going to assume this either a limitation or issue with localforage itself. I'd suggest testing out localforage directly (no Ionic), and opening an issue there

https://github.com/localForage/localForage
