### ISSUE TITLE
java.lang.OutOfMemoryError ionic 3

### ISSUE THREAD

**Issue by bimosatriantoro** [ionic-team/ionic-storage#157]
Hello,

Im using ionic-storage for my application. I save a lot of json data to my local storage. And every month i get this error 

> Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 75497480 byte allocation with 16769216 free bytes and 49MB until OOM

How i manage my local storage using ionic-storage in my app? Because my data is growth every day.

**Comment by mhartington** [comment]
Hi there! It appears this isn't really an issue, and more of a question, so Im going to close this. Please check out the [forum](https://forum.ionicframework.com) as this is a better place for questions. Thanks!
