### ISSUE TITLE
java.lang.OutOfMemoryError from storage.get

### ISSUE THREAD

**Issue by craigstanton** [ionic-team/ionic-storage#164]
I appear to haver created an item that is too big to get 

     `this.storage.get('storedSurveys').then(....`

Causes 

`java.lang.OutOfMemoryError`

I don't know if you'd count this as a bug, a question or a feature request but being able to write something that can't be read is a problem. Maybe there could be a way to check the size of a value before getting it.

@ionic/storage => v2.1.3

**Comment by mlynch** [comment]
Sorry, not sure if I can resolve this given the above info
