### ISSUE TITLE
Decorator support?

### ISSUE THREAD

**Issue by seiyria** [ionic-team/ionic-storage#166]
One of my favorite things about [ngx-webstorage](https://www.npmjs.com/package/ngx-webstorage) - another library I use frequently - is their ability to just `@Decorate()` a property, and writes will automatically persist to storage (as well, they are loaded when the component is).

I noticed there are no issues in the tracker about this. Is this something that may be supported in the future?

**Comment by mlynch** [comment]
Thanks, not on the roadmap but will consider it. Cheers!
