### ISSUE TITLE
storage.ready Promise not really ready in cordova with sqlite plugin

### ISSUE THREAD

**Issue by tobika** [ionic-team/ionic-storage#168]
Hi,
I'm using 
```
this.storage.ready().then(() => {
  console.log('ready');
});
```
to start accessing the storage. In the browser this works perfect. On android with the `cordova-sqlite-storage` I see that `ready` is logged to the console and then the debugging logs of the sqlite plugin start to appear. `DB open` and `DB opened`.

Which means that if I use `storage.get` in this tiny timeframe I don't receive the real values. I found out that sometimes it works, sometimes it doesn't, probably a performance question of the device.

After browsing through the code I see that ionic storage is returning the localForage instance.

https://github.com/ionic-team/ionic-storage/blob/2ea8583d774a96c3c150e944c8fe925d0cf69f3d/src/storage.ts#L134

A bit more browsing in the localForage docs shows that localForage also has a ready Promise that is not accounted for in the ionic storage.
https://localforage.github.io/localForage/#driver-api-ready

The workaround I use to be sure the sqlite db is loaded. I am just using the returend localForage object and listen again to the ready promise. Like this the everything is initialized and I can safely access my data afterwards.

```
this.storage.ready().then((localForage) => {
  console.log('ready');
  localForage.ready(() => {
      console.log('really ready');
  })
});
```

Ionic info
```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 10 other plugins)

System:

   NodeJS : v8.10.0 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.15
```

**Comment by wa05** [comment]
Hello this solution continued to serve you, I am with the same problem

**Comment by jrista** [comment]
Is there still a ready event in v3? We have a fairly specific use case where we need to read data from storage the moment ngrx effects in an ionic/angular app are initialized. The problem we have is there now only seems to be a storage.create() method, there is no longer appears to be storage.ready() method that we can block things on until storage is in fact ready to be used.

**Comment by jrista** [comment]
@mlynch The lack of a ready() promise is still an issue for us. We seem to run into cases where we try to use Storage before it's ready, which forces us to rely on delays, or retry loops, etc. This complicates code that could be quite simple if we could wait until the Storage driver(s) were ready...

**Comment by mlynch** [comment]
@jrista you don't need a ready() anymore. The old library had a hard coded `defineDriver` for the `CordovaSQLitePlugin` which was the only promise `ready()` had to wait on anyways.

Instead, explicitly wait on any `defineDriver` and after calling `create` the DB is ready to use.

Not sure if you're using angular but take look at the `init()` method here:

https://github.com/ionic-team/ionic-storage#with-angular
