### ISSUE TITLE
node_modules/@ionic/storage/fesm5/ionic-storage.js Module not found: Error: Can't resolve '@angular/core'

### ISSUE THREAD

**Issue by imashwanitiwari** [ionic-team/ionic-storage#170]
I m using ionic 4 storage module and i m getting following error

node_modules/@ionic/storage/fesm5/ionic-storage.js 
Module not found: Error: Can't resolve '@angular/core'

![image](https://user-images.githubusercontent.com/41265377/54886192-3fe72d80-4eab-11e9-875b-8a357c663028.png)

This is my service where i m using it.

![image](https://user-images.githubusercontent.com/41265377/54886212-8d639a80-4eab-11e9-8d8b-4bb53f8373e2.png)

As i go to the source my editor is also showing same problem

![image](https://user-images.githubusercontent.com/41265377/54886218-af5d1d00-4eab-11e9-8a8e-faf879565832.png)

I m new with angular and ionic please help me with this.
Thanks.

**Comment by priyankachitte** [comment]
This work for me
sudo npm install --save @ionic/storage --save
