### ISSUE TITLE
this.storage.get doesn't work after opening idle app

### ISSUE THREAD

**Issue by TitchyDean** [ionic-team/ionic-storage#171]
Hello all,

I have a weird issue that I've not seen before but hoping someone else has and can give me a clue.

When opening an idle app the **this.storage.get** fails but doesn't return an error, doesn't hit the catch...the promise from this.storage.get never resolves. It just doesn't seem to do anything at all. It does however work when opening the app for the first time, its just after opening from being idle.

I have tried wrapping a try, catch around it, doesn't get touched.

```
this.storage.ready().then((res) => {
  this.storage.get("favs").then((res) => {
     //Do stuff
  }).catch(err => { 
    console.log(err); 
  });
}).catch(err => { 
  console.log(err); 
});
```

```
"@angular/compiler": "5.2.10",
"@angular/compiler-cli": "5.2.10",
"@angular/core": "5.2.10",
"@ionic-native/core": "4.7.0",
"@ionic/storage": "^2.1.3",
"ionic-angular": "3.9.2"
```

**Comment by goldsun888** [comment]
I encountered the same problem. Any idea?

**Comment by alexarvanitidisalpha** [comment]
We are facing the same issue and solving it by running:

```typescript
localForage.setDriver('WEBSQL'); 
```

something like this, it re-initialises the connection

**Comment by goldsun888** [comment]
I solved it by adding sqlite plugin.

**Comment by smartin85** [comment]
Same issue here, even after restarting the app.
