### ISSUE TITLE
Data not accessible after upgrading from ionic 3 to ionic 4

### ISSUE THREAD

**Issue by Sebschock** [ionic-team/ionic-storage#172]
Hi, after updating my Ionic app from 3 to 4 I can no longer access stored data which means my users are logged out of the app when they upgrade.

The app upgrade works fine in the browser (via Ionic serve) i.e. the user is not logged out. 

When I deploy the app to iOS data is not accessible. I can see that the Ionic 3 app uses INDEXEDDB for storage on iOS and the Ionic 4 app uses webSQLStorage. 

I tried forcing iOS to use IndexedDB (`driverOrder: ['indexeddb']`) but I then get the error `Error: No available storage method found.`.

Any ideas to fix this? Thanks

**Comment by Sebschock** [comment]
I just figured out how to handle the issue, which is not caused by ionic-storage. I thought I would share my solution in case anybody finds this post.

In my old Ionic 3 app I install `ionic cordova plugin add cordova-sqlite-storage`. In the app.module.ts import I force the app to use the old db with: 
```
@NgModule({
...
imports: [
    ...
    IonicStorageModule.forRoot({driverOrder: ['indexeddb', 'sqlite', 'websql']}),
]
```

When the user is loaded from Ionic Storage, I create a new storage instance using sqlite and save the authToken to sqlite:
```
let newDB = new Storage({driverOrder: ['sqlite']})
newDB.ready().then(data => {
    newDB.set('transitionToken', authToken);
})
```

In my Ionic 4 app I also install cordova-sqlite-storage. When I try loading the user from Storage I check if the transitionToken is present. If so, I call the backend to login with the token: 

```
this.storage.get('transitionToken').then(authToken => {
    this.login(authToken).subscribe((data) => {
        ...
    })
```

Hope somebody find this useful :)

**Comment by geeksilva97** [comment]
> I just figured out how to handle the issue, which is not caused by ionic-storage. I thought I would share my solution in case anybody finds this post.
> 
> In my old Ionic 3 app I install `ionic cordova plugin add cordova-sqlite-storage`. In the app.module.ts import I force the app to use the old db with:
> 
> ```
> @NgModule({
> ...
> imports: [
>     ...
>     IonicStorageModule.forRoot({driverOrder: ['indexeddb', 'sqlite', 'websql']}),
> ]
> ```
> 
> When the user is loaded from Ionic Storage, I create a new storage instance using sqlite and save the authToken to sqlite:
> 
> ```
> let newDB = new Storage({driverOrder: ['sqlite']})
> newDB.ready().then(data => {
>     newDB.set('transitionToken', authToken);
> })
> ```
> 
> In my Ionic 4 app I also install cordova-sqlite-storage. When I try loading the user from Storage I check if the transitionToken is present. If so, I call the backend to login with the token:
> 
> ```
> this.storage.get('transitionToken').then(authToken => {
>     this.login(authToken).subscribe((data) => {
>         ...
>     })
> ```
> 
> Hope somebody find this useful :)

Thanks!!!
