### ISSUE TITLE
Vue 2.6 support?

### ISSUE THREAD

**Issue by heihachi88** [ionic-team/ionic-storage#173]
Doesn't work with Vue. I've installed it `npm i --save @ionic/storage`, then imported it:

```
import { Storage } from '@ionic/storage'
```

It throws me an error: 

```
This dependency was not found:

* @angular/core in ./node_modules/@ionic/storage/fesm5/ionic-storage.js

To install it, you can run: npm install --save @angular/core
```

So it does work only with Angular?

**Comment by dotNetkow** [comment]
Yes, and apologies that isn't more clear.  [Angular and Vanilla JS](https://ionicframework.com/docs/native/overview) only at the moment.

**Comment by mezerotm** [comment]
Are there any alternatives?

**Comment by mezerotm** [comment]
For anyone interested I created a workaround. Not perfect but works for my case.
https://gist.github.com/mezerotm/9fd42776fc6393971c08549162e91e16

**Comment by col-panic** [comment]
Aren't there any plans on implementing this?

**Comment by webcoderkz** [comment]
I ended up switching to flutter, much better. Ionic is too raw for production mobile apps, also on iOS it's unstable, after installing an app, after week it would crash.
