### ISSUE TITLE
Can i create a instance of storage outside of any component, provider,...? 

### ISSUE THREAD

**Issue by hamidb80** [ionic-team/ionic-storage#179]
Hello.
I want to access data faster, so I want to get all data at first ( when app opened ) and store it to a variable. Then I export it and use it.

Is it possible?

**Comment by mlynch** [comment]
You can access it as soon as your app starts to load assuming you are using Capacitor. If not then you'll need to do it after `deviceready` fires in Cordova which will be behind where Capacitor fires it
