### ISSUE TITLE
App size increasing after storing data in local storage and removing them

### ISSUE THREAD

**Issue by sharutza** [ionic-team/ionic-storage#181]
I store some data in local storage before sending them server-side, but after calling remove(key) or clear() the app size (UserData) in device's settings get's bigger and bigger. It seems like the app does not free the occupied resources after calling storage.clear() and my user have to go in phone's settings to clear the storage.

Thanks.

**Comment by mlynch** [comment]
Could be it's using two different storage engines somehow?

**Comment by brunocbatista** [comment]
Amazingly, I have the same problem. Has anything been done to fix it?
