### ISSUE TITLE
SQLLite doesn't delete all items after calling remove() method

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic-storage#183]
```typescript
private async removeItem(key = 'foo'): Promise<void> {
  await this.storage.remove(key);
}
```
then later:
```typescript
private async getItems(key = 'foo'): Promise< string[] | null> { 
  return await this.storage.get(key);
}
```
the return value is a partial array of what was _previously_ in foo. I have to call `remove()` twice for it to be completely removed...

**Comment by mlynch** [comment]
Sorry, not sure what is going on here, could be an oddity of that underlying driver which is out of scope for this.
