### ISSUE TITLE
iOS 13.4 and Safari 13.1 persistent storage

### ISSUE THREAD

**Issue by cyptus** [ionic-team/ionic-storage#184]
Like mentioned on https://github.com/localForage/localForage/issues/943 Apple announced to clear all script-writeable storages after 7 days of inactivity on WebKit in iOS 13.4 and Safari 13.1.

More info: https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/
Storages affected: `Indexed DB, LocalStorage, Media keys, SessionStorage, Service Worker registrations`

Will this also reflect on cordova apps using this plugin without sqllite and should be added to the readme.

Edit: i think native cordova apps should not be affected by this, as only domains that have been classified by ITP to track users are affected: https://webkit.org/blog/9521/intelligent-tracking-prevention-2-3/

**Comment by tofumatt** [comment]
To clarify: all sites visited by Safari are affected by this change, regardless of domain. There's more context in https://github.com/localForage/localForage/issues/943

But Cordova apps won't be affected by this because only Safari has ITP enabled; code using WebViews/WKWebView/etc. doesn't have ITP enabled so should be fine. 🙂

Only websites visited by Safari are affected.

**Comment by cyptus** [comment]
Thanks for clarification @tofumatt.

There are ionic apps which are deployed as web app / pwa which can be visited by Safari. At least they should be affected by this new limitations.

**Comment by tofumatt** [comment]
Ah, true! So yeah, the gist is that websites visited in Safari.app are affected; nothing else 😄

**Comment by thmclellan** [comment]
If I understand correctly, this means that any PWA apps using Ionic Storage (e.g. for storing JWT authentication tokens) will require their Safari users to re-login after 7 days, unless they add the website to their home screen on iOS.

**Comment by cyptus** [comment]
@thmclellan yes

**Comment by mhartington** [comment]
Hey everyone. Just catching this issue.

As it stands right now, the following is true:

- Storage mechanism in WKWebview are not affected by this change. So hybrid web apps are safe
- Web Apps saved to the home screen are also not affected by this change. See this tweet from Apple/Safari Devrel.

https://twitter.com/jonathandavis/status/1243228885006708737

- Web Apps accessed through Safari will have a 7 day timer on storage. If a user does not interact with a site, the storage will be deleted.  


This is all the information we have currently. There's still some confusion on the details, but there's been a lot of confirmation from Apple that this will not affect web apps. 

There's still a lot of question, like is the storage cleared from first-party or 3rd-party? Or both? We're observing the situation but would like to reassure that we are on top of this. 

Thanks
