### ISSUE TITLE
I can't set global variables from the @ionic/storage get method

### ISSUE THREAD

**Issue by ikennaUkwueze** [ionic-team/ionic-storage#186]
I have tried several times to modify the value of a global variable after I get the value from get method.

`this.storage.get('userInfo').then((data) => {
      this.userInfo = data;
      this.userId = data.id;
    });
    console.log(this.userId);`

Above is my code, `this.userId` returns undefined when I log it to the console outside the code block but returns the correct value when I log from inside the code block. Please help me, I need a way out, I can't afford to be querying the database each time.

**Comment by rapropos** [comment]
Please use [the forums](https://forum.ionicframework.com/) or Slack channel for support requests like this, instead of creating issues.

**Comment by KillerCodeMonkey** [comment]
@ikennaUkwueze just learn about async code... the log outside of the then-block is executed before the callback in the then block... so it is not set outside.

google for async await and promises ;-).

**Comment by ikennaUkwueze** [comment]
Okay thanks
