### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by zenhuw** [ionic-team/ionic-storage#187]
I got this error when i upgraded to angular 10

> [ng] node_modules/@angular/fire/firestore/firestore.module.d.ts:7:74 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
[ng] 7     static enablePersistence(persistenceSettings?: PersistenceSettings): ModuleWithProviders;

here is the link to the  [Angular migration doc](https://next.angular.io/guide/migration-module-with-providers) for this issue

**Comment by blondie63** [comment]
Hi, i've same issue but i don't understand how to add ModuleWithProviders
This my code:
```
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    IonicStorageModule.forRoot({
      name: '__mydb',
      storeName: '_settings',
      driverOrder: ['sqlite', 'websql', 'indexeddb']
    }),
```
Can you help me ? :)
Thanks
