### ISSUE TITLE
@ionic/storage + cordova-sqlite-storage + dbkey cipher

### ISSUE THREAD

**Issue by Hanzofm** [ionic-team/ionic-storage#189]
Hi,

Recently, I've noticed that:

 IonicStorageModule.forRoot({
      name: 'myname',
      driverOrder: ['sqlite', 'localstorage', 'indexeddb', 'websql']
    }),

Has an additional param call dbKey, This is to use cipher with my sqlite db + @ionic/storage.

Wich is the correct setup?:

@ionic/storage + cordova sqlite plugin + dbKey param on db startup/open

or

@ionic/storage + Cordova-sqlcipher-adapter + dbKey param on db startup/open

or

@ionic/storage + cordova sqlite plugin + Cordova-sqlcipher-adapter + dbKey param on db startup/open

Thanks

**Comment by mlynch** [comment]
Sorry, not sure. We will be supporting encryption in the next release through Ionic Secure Storage for teams that need it (premium feature), but you will be able to use other drivers through custom configuration if you so choose
