### ISSUE TITLE
2.3.0 breaks my build - An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by benallard** [ionic-team/ionic-storage#192]
```
Building Angular Package
Building entry point '@ns/project'
Compiling TypeScript sources through ngc


BUILD ERROR
node_modules/@ionic/storage/storage.d.ts(112,9): error TS1086: An accessor cannot be declared in an ambient context.

Error: node_modules/@ionic/storage/storage.d.ts(112,9): error TS1086: An accessor cannot be declared in an ambient context.

    at Object.<anonymous> (/home/user/jenkins/workspace/.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/jenkins/workspace/.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)

node_modules/@ionic/storage/storage.d.ts(112,9): error TS1086: An accessor cannot be declared in an ambient context.

Error: node_modules/@ionic/storage/storage.d.ts(112,9): error TS1086: An accessor cannot be declared in an ambient context.

    at Object.<anonymous> (/home/user/jenkins/workspace/.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/jenkins/workspace/.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@2020.33.0-devel build: `node --max_old_space_size=4200 node_modules/@angular/cli/bin/ng build "project"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@2020.33.0-devel build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-07-24T14_08_37_105Z-debug.log
script returned exit code 1
```

**Comment by shadowboxingskills** [comment]
Getting same error as @benallard 
Downgrading back to 2.2.0 solves the problem, indicating that 2.3.0 may have some back-compatibility issue

**Comment by paulovargatt** [comment]
same error  Downgrading back to 2.2.0 solves the problem !

**Comment by TechJorvis** [comment]
Same Error. Downgrading back to 2.2.0 using `npm i @ionic/storage@2.2.0` solves the problem !

**Comment by calvinckho** [comment]
also I noticed 2.3.0 fails in my electron build. It failed to write to IndexedDB. Downgrading it to 2.2.0 solves the problem for me.

**Comment by mhartington** [comment]
Thanks all, I'll take a look

**Comment by mhartington** [comment]
Would someone be able to provide a minimum example?

**Comment by TechJorvis** [comment]
> Would someone be able to provide a minimum example?

`npm i @ionic/storage@2.2.0`

**Comment by mhartington** [comment]
@TechJorvis That is **not** a minimal example. 

From a few comments with other community members, they mentioned being on Angular 7.x.x, which is really old.
Please upgrade your angular version of stay pinned to 2.2.0 of Ionic storage.

**Comment by EvenJulianIntellect** [comment]
Same issue faced with angular version 8 also. Resolved by downgrading to 2.2.0.

```
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
[ng]
[ng] ERROR in ../node_modules/@ionic/storage/storage.d.ts:112:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 112     get driver(): string | null;
```

Ionic info:
```
Ionic:

   Ionic CLI                     : 5.4.5 
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.28
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.3.28
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:
   cordova-res : 0.14.0 
   native-run  : 0.2.9 

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v10.13.0 
   npm               : 6.4.1
   OS                : Windows 10
```

**@mhartington Team, would be really helpful if such version compatibility issues (if left open) are tracked in the documentation for that plugin. TIA!**

**Comment by Riekr** [comment]
Same for me with angular 8 again:
`Ionic:

   Ionic CLI                     : 6.11.0 (/home/x/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 14 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/home/x/Projects/Android/Sdk)
   NodeJS            : v12.16.3 (/usr/bin/node)
   npm               : 6.14.7
   OS                : Linux 5.7`

**Comment by mhartington** [comment]
Please stay on 2..0 then if you are stuck on older versions of angular and typescript.
