### ISSUE TITLE
An error occurred while running subprocess ionic-app-scripts, Ionic Storage errors.

### ISSUE THREAD

**Issue by StephSince93** [ionic-team/ionic-storage#195]
I have recently made some small changes to my Ionic 3 app and I'm running a production build, but seem to be Ionic Storage errors during build-time. I'm not sure what exactly changed, or what needs to change in order to get this app to build.

[10:21:50]  typescript: ../node_modules/@ionic/storage/storage.d.ts, line: 112 
            An accessor cannot be declared in an ambient context. 

     L111:  get driver(): string | null;
     L113:   * Reflect the readiness of the store.

[10:21:50]  typescript: ../node_modules/@ionic/storage/index.d.ts, line: 5 
            Type 'ModuleWithProviders' is not generic.

       L4:  export declare class IonicStorageModule {
       L5:      static forRoot(storageConfig?: StorageConfig): ModuleWithProviders<IonicStorageModule>;
[10:21:50]  ionic-app-script task: "build" 
[10:21:50]  Error: The Angular AoT build failed. See the issues above
Ionic:

 Ionic:

   Ionic CLI          : 5.4.15 
   Ionic Framework    : ionic-angular 3.9.10
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 12 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : not installed

System:

   NodeJS : v10.18.0 
   npm    : 6.12.0
   OS     : Windows 10

package.json:

{
  "name": "test",
  "version": "1.5.2",
  "author": "test",
  "homepage": "",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@ionic-native/app-version": "^4.20.0",
    "@ionic-native/camera": "^4.20.0",
    "@ionic-native/core": "4.11.0",
    "@ionic-native/device": "^4.20.0",
    "@ionic-native/email-composer": "^4.20.0",
    "@ionic-native/file": "^4.20.0",
    "@ionic-native/file-transfer": "^4.20.0",
    "@ionic-native/geolocation": "^4.20.0",
    "@ionic-native/ionic-webview": "^5.5.1",
    "@ionic-native/network": "^4.20.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/app-scripts": "^3.2.3",
    "@ionic/pro": "^2.0.4",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular2-signaturepad": "^2.8.0",
    "cordova": "^9.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-build-increment": "^0.1.0",
    "cordova-ios": "5.1.1",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-email-composer": "^0.8.15",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-file-transfer": "1.7.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic": "5.3.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.4.1",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-webview": "0.0.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^3.2.0",
    "ionic-angular": "^3.9.5",
    "ionic-select-searchable": "^2.10.0",
    "ionic-selectable": "^3.4.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "ts-md5": "^1.2.4",
    "ws": "^3.3.3",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-device": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-email-composer": {},
      "cordova-plugin-file": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-ionic": {
        "APP_ID": "",
        "CHANNEL_NAME": "",
        "UPDATE_METHOD": "",
        "UPDATE_API": "",
        "MAX_STORE": "1",
        "MIN_BACKGROUND_DURATION": "30"
      }
    },
    "platforms": [
      "browser",
      "ios"
    ]
  }
}

Help Appreciated!

**Comment by mhartington** [comment]
Downgrade you're ionic storage release. The latest releases only support Angular 9 and up.
