### ISSUE TITLE
Web Storage API compliant ?

### ISSUE THREAD

**Issue by davidquintard** [ionic-team/ionic-storage#198]
Hi there,
I want to use https://github.com/btroncone/ngrx-store-localstorage
in combination with ionic storage but interface must conform to:
https://developer.mozilla.org/en-US/docs/Web/API/Storage

Why Ionic Storage is not compliant with Web Storage API ?

Regards

**Comment by mlynch** [comment]
Sorry, the API does not conform to Web Storage API so you'd need a driver that is compatible with localForage. That is something we will consider though, thanks.
