### ISSUE TITLE
Android 11 Support + Android SDK Target 30

### ISSUE THREAD

**Issue by jumamfa** [ionic-team/ionic-storage#200]
Hello,

I'm having difficulty using Ionic Storage + Cordova SQLite Storage.

Works absolutely fine if the target SDK is < 30.

Bump it to 30 (as I need to for another plugin in use) and it suddenly errors.

https://github.com/storesafe/cordova-sqlite-storage/issues/954
https://github.com/ionic-team/ionic-storage/issues/196

I've read on other posts that it appears SQLite works fine standalone on SDK 30, Android 11, but in combination with Ionic Storage, it fails.

Cordova: 10
Android: 9
Ionic Storage: 2.3.1
Cordova SQLite Storage: 5.1.0

Thanks

**Comment by jumamfa** [comment]
If I used SQLlite plugin directly, it opens the database fine with the below example

      var db = (window as any).sqlitePlugin.openDatabase({
        name: 'my.db',
        location: 'default',
        androidDatabaseProvider: 'system'
      });

If however I remove the androidDatabaseProvider, same failure as ionic storage, it cannot open the database..

**Comment by mhartington** [comment]
Closing as duplicate of https://github.com/ionic-team/ionic-storage/issues/196

**Comment by AleffBruno** [comment]
to fix it you must

$ rm -R platforms
$ rm -R plugins

in package.json update/add this
"cordova-sqlite-storage": "6.0.0",

add platform ( in case you are using android10, use this $ ionic cordova platform add android@10.0.0  )

after this look inside plugins/cordova-sqlite-storage/plugin.xml if the version is 6.0.0

**Comment by jakisondev** [comment]
I performed all possible solutions described but the problem still persists.
If there is any other possible solution, thank you.
