### ISSUE TITLE
Storage not persist after closes tab or reload app on browser

### ISSUE THREAD

**Issue by Hanzofm** [ionic-team/ionic-storage#207]
Hi all

**Problem:**

When store info with ionic-storage  while the webapp is running the info persist and get/set works as expected. If I store info and close webapp tab o reload app from browser the info disappears.

_Same Project works as expected running into a android/ios Platform._

**This is my configuration on app.module:**

```
  IonicStorageModule.forRoot({
            name: 'MyAppDB',
            driverOrder: ['sqlite', 'localstorage', 'indexeddb', 'websql'],
        }),
```

**These are my env versions:**

```
Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
"@ionic/storage": "2.3.1",
"cordova-browser": "^6.0.0",
"cordova-sqlite-storage": "^5.1.0",
```
**Compile webapp with:**

`ionic cordova build browser --prod`

And upload 'www' folder to 'AWS'

Some solution or workaround? Someone managed with this?

**Comment by NiklasMerz** [comment]
The SQlite driver does not persist the data on the browser platform. Because ionic storage is using SQlite your data will just be stored in memory.

**Comment by mlynch** [comment]
Yea the data is stored in different ways when running on web and when running natively, since the engine will use `sqlite` in your above config on native, but fallback to `localstorage` on web
