### ISSUE TITLE
Locked sqlite3 database issue (Android)

### ISSUE THREAD

**Issue by olidotjpeg** [ionic-team/ionic-storage#208]
Hey hey,

I am having some issues in an Ionic app I am using, while using the ionic storage I get the following error in a lot of user instances `Uncaught (in promise): Object: {"message":"sqlite3_step failure: database is locked","code":0}`.

I see that a lot of issues on this plug redirect to the sqlite3 plugin to fix bugs there, but I believe this bug *could* be fixed by enabling the `androidDatabaseProvider: 'system'` setting, which doesn't seem to be possible when using this event.

Is there a way to expose the settings of the sqlite3 plugin through the ionic-storage provider?

**Comment by mlynch** [comment]
Would recommend posting that over at https://github.com/thgreasi/localForage-cordovaSQLiteDriver as that's not something we can address from our end. Thanks.
