### ISSUE TITLE
@ionic/storage locked its dependency on localforage to 1.7.1, and is causing the error `Duplicate identifier 'localforage'`

### ISSUE THREAD

**Issue by rogerfachini** [ionic-team/ionic-storage#209]
@ionic/storage version: 2.3.1

A dependency (Sentry) in my project also uses LocalForage. The dependency supports LocalForage versions >= `1.8.1`, while Ionic Storage is locked to LocalForage version `1.7.1`. When building the project with both versions of LocalForage present, the build fails with the following error:
```
ERROR in node_modules/@sentry/integrations/node_modules/localforage/typings/localforage.d.ts:122:14 - error TS2300: Duplicate identifier 'localforage'.

122     export = localforage;
                 ~~~~~~~~~~~

node_modules/localforage/typings/localforage.d.ts:122:14
  122     export = localforage;
                   ~~~~~~~~~~~
  'localforage' was also declared here.
node_modules/localforage/typings/localforage.d.ts:122:14 - error TS2300: Duplicate identifier 'localforage'.

122     export = localforage;
                 ~~~~~~~~~~~

  node_modules/@sentry/integrations/node_modules/localforage/typings/localforage.d.ts:122:14
    122     export = localforage;
                     ~~~~~~~~~~~
    'localforage' was also declared here.
```

`node_modules/localforage` is the package installed by @ionic/storage, while `node_modules/@sentry/integrations/node_modules/localforage` is the version installed by Sentry. 

This exact dependency conflict was present in previous versions of Sentry (see getsentry/sentry-javascript#3132) and has been resolved. I've since updated Sentry in my project, however the dependency conflict still exists in @ionic/storage.

**Comment by caox2110** [comment]
I have the same problem, any solution? Thx

**Comment by mlynch** [comment]
Dependency is updated in v3, going to close. Thanks
