### ISSUE TITLE
UnsatisfiedLinkError when opening SQLite storage

### ISSUE THREAD

**Issue by NLueg** [ionic-team/ionic-storage#210]
Hi there, I recently published a version of our app with the sqlite plugin.
It works pretty well for most users but there are currently 2 devices that crash because of the exception below.

- Galaxy S8 (Android 9)
- Pixel 3 XL (Android 9)

![image](https://user-images.githubusercontent.com/48101693/107634314-9f9a7d80-6c69-11eb-9aa3-feacaedaf6b3.png)

I actually would expect that one of the other storages are used if the SQLite instantiation fails.

**Comment by mlynch** [comment]
Thanks for the issue, looks like an issue with that specific driver so going to close as it's not something we can fix here. Suggest posting that here https://github.com/thgreasi/localForage-cordovaSQLiteDriver
