### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by N0ps32** [ionic-team/ionic-storage#214]
I was just updating my dependencies when I saw that Version 3.x was released but I couldn't find any information in the changelog about breaking changes. Can I just upgrade from 2.x without any changes? I saw the readme mention @ionic/storage-angular but I couldn't find that package on NPM

**Comment by mlynch** [comment]
Updated, thanks. Let me know if that doesn't have what you're looking for: https://github.com/ionic-team/ionic-storage/blob/main/CHANGELOG.md

**Comment by mlynch** [comment]
Also sorry the package was marked private but is now public: https://www.npmjs.com/package/@ionic/storage-angular
