### ISSUE TITLE
(Documentation): No Provider for Storage

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-storage#215]
I just migrated to 3.x and had to add **Storage** (from `'@ionic/storage'`) to the Modules **providers**. Otherwise i could not start the App because: `No Provider for Storage`.

Is this correct? If so, it should be added to the Documentation

**Comment by mlynch** [comment]
You shouldn't need to do that. This is all you need to configure it in your app:

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { FormsModule } from '@angular/forms';
import { HomePage } from './home.page';

import { HomePageRoutingModule } from './home-routing.module';

import { IonicStorageModule } from '@ionic/storage-angular';


@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    HomePageRoutingModule,
    IonicStorageModule.forRoot()
  ],
  declarations: [HomePage]
})
export class HomePageModule { }
```

**Comment by EinfachHans** [comment]
That does not work. Here is someone with the same Problem: https://forum.ionicframework.com/t/ionic-storage-angular-new-api/206667/4?u=einfachhans

**Comment by mlynch** [comment]
Something's not right. I have a demo app where this works perfectly. Are you using `@ionic/storage-angular`?

**Comment by EinfachHans** [comment]
Yes I'm importing:
```ts
import { IonicStorageModule } from '@ionic/storage-angular';
import * as CordovaSQLiteDriver from 'localforage-cordovasqlitedriver';
import { Drivers } from '@ionic/storage';
```

and in my **app.module**: 
```ts
imports: [
    ...
    IonicStorageModule.forRoot({
      driverOrder: [CordovaSQLiteDriver._driver, Drivers.IndexedDB, Drivers.LocalStorage]
    }),
    ...
]
```

**Comment by mlynch** [comment]
And then what `Storage` are you using in your constructor?

Needs to be 

```typescript
import { Storage } from '@ionic/storage-angular'

constructor(private storage: Storage) {}
```

**Comment by EinfachHans** [comment]
Ahh there we have the Problem. [Here](https://github.com/ionic-team/ionic-storage/blob/main/README.md#with-angular) it says to import like `import { Storage } from '@ionic/storage';`

**Comment by mlynch** [comment]
Ah, my bad. Fixed. With that it's working fine?

**Comment by mlynch** [comment]
Closing as I believe this is fixed. Thanks for the help

**Comment by EinfachHans** [comment]
Yes works 😊 Sorry for delayed response
