### ISSUE TITLE
Uncaught (in promise): TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by Remonell** [ionic-team/ionic-storage#218]
Hi, 
my code tries to get values from the storage, before this._storage has a value. That results in the error message from the title.
How can I make sure, that this._storage has a value before any of the classes methods gets called?

Kind regards

```

export class StorageService {
  private _storage: Storage | null = null;

  constructor(private storage: Storage) {
    this.init();
  }

  async init(){
    const storage = await this.storage.create();
    this._storage = storage;
  }

  async set(key: string, value:any) {
    const encryptedValue = btoa(escape(JSON.stringify(value)));

    await this._storage?.set(KEY_PREFIX+key,encryptedValue);
  }

  async get(key:string): Promise<any> {
    const item = await this._storage?.get( KEY_PREFIX + key );

    if (item.value) {
      return JSON.parse(unescape(atob(item.value)));
    } else {
      return null;
    }
  }
}
```

**Comment by mlynch** [comment]
I would recommend checking that create worked in the methods you need to access the database in. So `set` and `get` should both first check to make sure the db was created.

And also you should change `item.value` to `item?.value`

**Comment by francoisduchemin** [comment]
Hi Remonell,

how did you solve the issue in the end? I was thinking about adding an observable in the StorageService:

`private isStorageCreated = new BehaviorSubject(false);`

When the storage is created I would set it to true:

```
   async init(){
    const storage = await this.storage.create();
    this.isStorageCreated.next(true);
    this._storage = storage;
  }
```

Then I would get values from storage only if the storage is created:  

```
this.storageService.isStorageCreatedObservable().subscribe(isStorageCreated => {
  if (isStorageCreated) {
    // get values from the storage 
  }
});
```

What do you think?

**Comment by Remonell** [comment]
Hi francoisduchemin,

here is how I solved it:

```
async init() {
    if (!this._storage) {
      const storage = await this.storage.create();
      this._storage = storage;
    }
  }

  async getKeys(): Promise<any> {
    if (!this._storage) {
      await this.init();
    }

    return await this._storage?.keys();
  }

```

Your approach seems much cleaner and should also work. If it works for you I will rewrite my code. Did you already implement it?

**Comment by francoisduchemin** [comment]
Thanks for your answer! I did not implement it yet but I'm not sure if it's cleaner... I like the simplicity of your solution!
I think I'm going to implement it like you...
