### ISSUE TITLE
Does changing order of the storage automatically migrate the data.

### ISSUE THREAD

**Issue by ir2pid** [ionic-team/ionic-storage#235]
We were using the default order to store our data and would like to change it to use sql instead. 

Does the plugin take care of migration to secure storage when we change the order or it has to be done manually?

**Comment by mlynch** [comment]
No it does not. However, if you want to encrypt an existing SQLite database when moving to Ionic Secure Storage, we have some docs on that: https://github.com/ionic-team/ionic-storage#encrypting-an-existing-sqlite-database
