### ISSUE TITLE
Ivy distibution for angular 13

### ISSUE THREAD

**Issue by WolfWalter** [ionic-team/ionic-storage#249]
When I build my angular+ionic app, the `ionic-storage` package is the last view engine library:
```
ng run app:serve --host=localhost --port=8101
[ng] - Generating browser application bundles (phase: setup)...
[ng] Processing legacy "View Engine" libraries:
[ng] - @ionic/storage-angular [es2015/esm2015] (git+https://github.com/ionic-team/ionic-storage.git)
[ng] Encourage the library authors to publish an Ivy distribution.
```

**Comment by JumBay** [comment]
Would be great to upgrade to ivy

**Comment by joaquinjsb** [comment]
bumping this up.

**Comment by broomfn** [comment]
+1 for Ivy

**Comment by bdirito** [comment]
Angular 15 has released, which now *only* has an ivy render engine.

https://github.com/angular/angular/pull/47346

It looks like angular can use the view engine binaries provided via transpiling them for now, but just point of motivation to upgrade for ivy.

**Comment by parksmart-dev** [comment]
+1 for this.

**Comment by franco-sch** [comment]
+1 for this

**Comment by thiboot** [comment]
+1 for ivy upgrade :-)
