### ISSUE TITLE
Still not fixed. Issue closed but unresolved

### ISSUE THREAD

**Issue by Alphayeeeet** [ionic-team/ionic-storage#261]
When importing IonicStorageModule of @ionic/angular-storage. IDE still shows Error in Angular as it seems to be no NgModule.

Im using @ionic/storage-angular version 3.0.6

VSCode shows following error:

'IonicStorageModule' does not appear to be an NgModule class.(-996002)
index.d.ts(7, 5): This likely means that the library (@ionic/storage-angular) which declares IonicStorageModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

#190

**Comment by Alphayeeeet** [comment]
Seems to be an vscode bug. Compiling works either way

**Comment by darthleonard** [comment]
publish an Ivy distribution please :)

![imagen](https://user-images.githubusercontent.com/5916018/202362526-8e394b83-cccd-40a8-8862-34393704cbfe.png)
