### ISSUE TITLE
Easier way to get the whole storage key/values

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-storage#27]
Could be a nice feature to create a `getDB()` to return the whole storage.

**Comment by tmvnk** [comment]
+1 
Or remove the whole DB

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic-storage/blob/master/src/storage.ts#L122

**Comment by mhartington** [comment]
Closing for now, as forEach is a good alternative.
