### ISSUE TITLE
iOS 16.1 SDK update clears ionic storage

### ISSUE THREAD

**Issue by alphagamer7** [ionic-team/ionic-storage#295]
## Bug Report

ionic-storage version
```
Ionic Capacitor versions 4 & 5.
ionic/storage-angular - 3.0.6
ionic/storage - ^2.3.0",
```

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.1
  @capacitor/android: 5.0.1
  @capacitor/ios: 5.0.1

Installed Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.1
  @capacitor/android: 5.0.1
  @capacitor/ios: 5.0.1
```

### Current Behavior
Earlier used iOS 15.5 SDK and the application kept the ionic storage(indexed db) however with the new iOS 16.1 SDK build, the ionic storage is cleared so previous data stored is lost. 

Migrated the app to Capacitor 5, but the issue remains. 

### Expected Behavior
Don't clear storage after the new iOS16.1 update.

Any possible solution to keep the existing data?

**Comment by liamdebeasi** [comment]
Have you filed an issue with Apple? Ionic Storage should not be wiping IndexedDB on OS upgrade.
