### ISSUE TITLE
Suggestion: Support serialization of TypeScript class objects

### ISSUE THREAD

**Issue by gammelby** [ionic-team/ionic-storage#60]
It would be nice with out-of-the-box support for serialization of class objects, currently all class info is silently lost if storing/restoring a TypeScript object. For instance, integrate with https://www.npmjs.com/package/serializer.ts.

**Comment by NoNameProvided** [comment]
This would be pretty hard to do, as how would ionic-storage find out which class to use for deserialization? Also how it should react if something changes in the class definitions? This features sounds like a lot more like an userland feature. 

A very basic implementation can be: 

```typescript
import { Storage } from '@ionic/storage';
import { deserialize } from "serializer.ts/Serializer";

export class CacheStorage {

  constructor(private storage: Storage) {
   
   }
  
  /**
   * Get the requested resource and cast it to the specified type.
   * @param key key identifying the requested resource
   * @param classType class of the requested resource
   * @returns Promise resolved with the value casted to the specified type
   */
  get<T>(key: string, classType: any): Promise<T> { 
    return this.storage.get(key).then( value => {
      return deserialize<T>(classType, value);  
    })
  }
}
```

**Comment by gammelby** [comment]
As for which class to use, the caller could specify the class name to use by the deserializer and then cast a general object returned. 

I still think such out of the box support would make sense with ionic2 - the framework is based on TypeScript so you should be able to store TypeScript objects without any hassle (such as installing typings, installing serializer.ts, writing custom code).

**Comment by mlynch** [comment]
Some kind of ORM? Sounds interesting, not in the current scope or plans but will keep open to gather thoughts/opinions

**Comment by gammelby** [comment]
I think ORM features are a bit overkill for something as conceptually simple as Ionic storage. Serialize to a blob and deserialize back again is sufficient, you don't care about the actual representation in storage. Just as how local storage (or Ionic storage) is typically used with JSON objects - with the addition of correctly marshalling class information so it can be cleanly used with TypeScript class instances.

**Comment by mhartington** [comment]
Closing for now.
