### ISSUE TITLE
storage.get multiple keys

### ISSUE THREAD

**Issue by wsknorth** [ionic-team/ionic-storage#70]
Would be nice to have a get for multiple keys like in NG2-Translate
```javascript
this.storage.get(['someKey', 'anotherKey'])
  .then((data) => {
    console.log(`${data.someKey}, ${data.anotherKey}`)
  })

**Comment by NoNameProvided** [comment]
This can be easily implemented in userland: 

```ts
getMultiple(keys: string[]) {
  const promises = [];

  keys.forEach( key => promises.push(this.storage.get(key)) );

  return Promise.all(promises).then( values => {
    const result = {};
    
    values.map( (value, index) => { 
      result[keys[index]] = value; 
    });

    return result;
  });
}
```

Ofc, this wont work if any of the keys doesn't exists. To return with a partial result, you can create some counter, and check whether all the promises have been resolve or rejected.

**Comment by capcom-r** [comment]
I accomplished it like this:

```
    this.storage.forEach( (value, key, index) => {
      if (key == 'token') { this.token = value }
      // Search for whatever you're looking for using if/else statements
    }).then(() => {
      // Do your thing
    });
```

**Comment by NoNameProvided** [comment]
@capcom-r that solution wont perform well when your stores grow. You are checking **every** key in the store regardless how many keys you actually want to get.

**Comment by danielsogl** [comment]
@NoNameProvided I will implement that feature! Give me one day :P

**Comment by NoNameProvided** [comment]
@jianminLee this seems like a separate issue, you should open a new issue for this.

**Comment by jianminLee** [comment]
@NoNameProvided ok ! I will build a new issue

**Comment by giovannipds** [comment]
I was also trying something like @capcom-r suggested, given the example (trying to get every single key called "country" + something, like country1, country2, country3 etc.):

    getAllFromStorage() {
      let arr = [];
      return this.storage.forEach((v, k, i) => {
          if (k.indexOf('country') !== -1)
            arr.push(v);
        }).then(() => {
          return Promise.resolve(arr);
        });

It's working on desktop serve, but gonna checks @NoNameProvided code after what @jianminLee metioned.

**Comment by zubair1024** [comment]
Brillant suggestion! @NoNameProvided

**Comment by mifkys** [comment]
any updates?

**Comment by mhartington** [comment]
Hi there! I think we'll pass on this option for now. If someone submits a PR, I'd happily review it though.

**Comment by SkoZombie** [comment]
It's a great suggestion from @NoNameProvided  but IMHO it's a rather convoluted solution to need to do EVERY time you want multiple items, so there should be an easier way, or at least a wrapper, to do this in the library itself.
