### ISSUE TITLE
fix import

### ISSUE THREAD

**Issue by igoreliasm** [ionic-team/ionic-storage#91]
Is the first time I use **ionic-storage**.
When I was importing the `IonicStorageModule` like the documentation:

`import { IonicStorageModule } from '@ionic/storage';
`

I got a error, so I went to `@ionic/storage` and saw that just `Storage` was exporting:

`export { Storage };
`

It's a bug and a reason for a PR?

**Comment by afreix** [comment]
I am experiencing the same issue: 

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002

And my package.json:

"dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic-native/core": "^3.2.0",
    "@ionic-native/facebook": "^3.2.0",
    "@ionic/storage": "2.0.0",
    "angularfire2": "2.0.0-beta.8",
    "firebase": "3.6.7",
    "ionic-angular": "^2.3.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],

**Comment by igoreliasm** [comment]
@afreix follow my example and import only { Storage } it works very well while we don't have sure.

**Comment by afreix** [comment]
Thanks I think I'm using the same workaround as you

`export function provideStorage() {
 return new Storage();
}` 

and 

`providers: [
     {provide: Storage, useFactory: provideStorage},
]`

in my app.module.ts

**Comment by DennisSmolek** [comment]
Not sure what's happening on your end but I'm importing as the docs say and I have it...
My definition trace of `IonicStorageModule` is:
```
/@ionic/storage/es2015/index.d.ts:4
/@ionic/storage/es2015/index.js:5
/@ionic/storage/es2015/index.ngfactory.d.ts:8
/@ionic/storage/es5/index.d.ts:4
/@ionic/storage/es5/index.js:7
/@ionic/storage/es5/index.ngfactory.ts:11
/@ionic/storage/es5/index.ngfactory.ts:12
/@ionic/storage/es5/index.ngfactory.ts:16
/@ionic/storage/es5/index.ngfactory.ts:17
/@ionic/storage/es5/index.ngfactory.ts:27
```

Are you remembering to do the `.forRoot()`?

**Comment by jeffgodwyll** [comment]
So I got the same error following the docs, then I found: https://github.com/driftyco/ionic-storage/releases/tag/v2.0.0

> @danbucholtz danbucholtz released this 24 days ago · 8 commits to master since this release
> 
> Moved to NgModule to resolve dependency injection issue.
> 
> Update Steps:
> 
> - Run `npm install @ionic/storage@2.0.0 --save --save-exact`
> - Remove Storage from your providers in `app.module.ts`
> - `import { IonicStorageModule } from '@ionic/storage'` instead of `import { IonicStorage } from '@ionic/storage'` in app.module.ts
> - Add `IonicStorageModule.forRoot()` to the imports array in `app.module.ts`

Hope it helps!

**Comment by jgw96** [comment]
Hello everyone, thanks for opening an issue with us! So i think im misunderstanding the issue here. Are you guys all running version 2.0.1 of storage? Also, you can look at [this branch](https://github.com/driftyco/ionic-conference-app/tree/lazy-load) of the conf app for an example of how to use version 2.0.1 of Ionic storage.

**Comment by igoreliasm** [comment]
@jgw96 tks for your reply here, I did not try to import it with the version you said, but I'm using the version 2.2.1 and the last version is 2.2.2 following the [npm](https://www.npmjs.com/package/ionic) 

Try to install the last version and import the Storage like the doc, probably you will get a error.

**Comment by DennisSmolek** [comment]
I am on 2.2.1 for `@ionic/cli` and 2.0.1  for `@ionic/storage` and not having the issue. You must switch the the `ngModule` version, Import the module, then use `.forRoot()` on your main `appModule`.

Can you show your `appModule` page? Here's one from something I've been playing with so ignore the added components/services: 

``` javascript
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { IonicStorageModule } from '@ionic/storage';
import { MyApp } from './app.component';
import { HelloIonicPage } from '../pages/hello-ionic/hello-ionic';
import { ItemDetailsPage } from '../pages/item-details/item-details';
import { ListPage } from '../pages/list/list';
import { InitializePage } from '../pages/initialize/initialize';
import { InitializeModal } from '../components/initialize-modal/initialize-modal';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { SecureStorage } from '@ionic-native/secure-storage';

// Roam Service
import { ScreenService } from '../providers/screen-service';
import { DataService } from '../providers/data-service';
import { LogService } from '../providers/log-service';
import { AuthService } from '../providers/auth-service';



@NgModule({
  declarations: [
    MyApp,
    HelloIonicPage,
    ItemDetailsPage,
    ListPage,
    InitializePage,
    InitializeModal
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot(),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HelloIonicPage,
    ItemDetailsPage,
    ListPage,
    InitializePage,
    InitializeModal
  ],
  providers: [
    StatusBar,
    SplashScreen,
    AuthService,
    LogService,
    SecureStorage,
    ScreenService,
    DataService,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
```

**Comment by mhartington** [comment]
Closing as this is most likely not relevant any more. Please open a new issue if this is still a problem. Thanks!
