### ISSUE TITLE
Please add ChangeLog

### ISSUE THREAD

**Issue by tkem** [ionic-team/ionic-storage#93]
I noticed (via `npm outdated`) that v2.0.1 is available, but without a proper change log it's hard to find out what's actually changed, and whether updating will do any harm (i.e. incompatibilities)...

**Comment by tkem** [comment]
Same for v2.1.1...

**Comment by mhartington** [comment]
So sorry for the delay! Will add this!

**Comment by tkem** [comment]
Great!

**Comment by mhartington** [comment]
A bit sparse (as we never really followed a convention), but a change log is up, and will be auto-generated in future releases
